# Generated by Django 2.1.5 on 2019-02-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='titulo',
            field=models.CharField(default='titulo', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='topico',
            field=models.CharField(default='topico', max_length=250),
            preserve_default=False,
        ),
    ]
