# Generated by Django 2.1.5 on 2019-02-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0003_auto_20190203_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='post',
            name='materia',
            field=models.CharField(max_length=250, verbose_name='matéria'),
        ),
    ]
